### PR TITLE
Fix error triggered by new analytics account or no data.

### LINKED ISSUE #18: exception with new analytics - without data
Trying to access array offset on value of type null {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /.../vendor/tightenco/nova-google-analytics/src/PageViewsMetric.php:42)

```
'previous' => $analyticsData->first()['pageViews'],
'result' => $analyticsData->last()['pageViews'],
```

### PR DESCRIPTION
**Pull request by krievley**
This pull request closes #18 by adding a default value of zero to the analytics metric when no data is returned.

Screen Shot 2021-01-15 at 10 59 28 AM

### CODE REVIEW

File: src/PageViewsMetric.php [hunk 1]
```diff
@@ -39,46 +40,80 @@ private function pageViewsOneDay()
...
 
         return [
-            'previous' => $analyticsData->first()['pageViews'],
-            'result' => $analyticsData->last()['pageViews'],
+            'result' => ($analyticsData && $analyticsData->last())
+                            ? $analyticsData->last()['visitors']
+                            : 0,
+            'previous' => ($analyticsData && $analyticsData->first())
+                            ? $analyticsData->first()['visitors']
+                            : 0,
```
Comment (mattstauffer) [inline src/PageViewsMetric.php]:
```suggestion
            'result' => $analyticsData->first()['pageViews'] ?? 0,
            'previous' => $analyticsData->last()['pageViews'] ?? 0,
```

File: src/PageViewsMetric.php [hunk 2]
```diff
@@ -39,46 +40,80 @@ private function pageViewsOneDay()
...
+            'ga:pageviews',
+            [
+                'metrics' => 'ga:pageviews',
+                'dimensions' => 'ga:yearMonth',
+            ]
+        );
+
+        $previousResults = collect($previousAnalyticsData->getRows());
 
         return [
```
Comment (mattstauffer) [inline src/PageViewsMetric.php:73]: same fix here

File: src/PageViewsMetric.php [hunk 3]
```diff
@@ -39,46 +40,80 @@ private function pageViewsOneDay()
...
             [
                 'metrics' => 'ga:pageviews',
                 'dimensions' => 'ga:year',
             ]
         );
 
-        $results = collect($analyticsData->getRows());
+        $previousResults = collect($previousAnalyticsData->getRows());
 
         return [
```
Comment (mattstauffer) [inline src/PageViewsMetric.php:104]: same thing here

File: src/VisitorsMetric.php [hunk 4]
```diff
@@ -28,60 +29,91 @@ public function calculate(Request $request)
...
 
     private function visitorsOneDay()
     {
         $analyticsData = app(Analytics::class)
             ->fetchTotalVisitorsAndPageViews(Period::days(1));
 
-        $yesterday = $analyticsData->first();
-        $today = $analyticsData->last();
-
         return [
```
Comment (mattstauffer) [inline src/VisitorsMetric.php:41]: same here

**Review by mattstauffer — CHANGES_REQUESTED** [review]
